name: CI
on: [push, pull_request]

jobs:
  test:
    name: Run Unit tests
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pod
        run: |
          cd TestObjectiveDropbox
          pod install --repo-update
      - name: Test iOS
        env:
          FULL_DROPBOX_API_APP_KEY: ${{ secrets.FULL_DROPBOX_API_APP_KEY }}
          FULL_DROPBOX_API_APP_SECRET: ${{ secrets.FULL_DROPBOX_API_APP_SECRET }}
          FULL_DROPBOX_USER_OAUTH2_TOKEN: ${{ secrets.FULL_DROPBOX_USER_OAUTH2_TOKEN }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild -workspace TestObjectiveDropbox/TestObjectiveDropbox.xcworkspace/ -scheme TestObjectiveDropbox_iOS -sdk iphonesimulator \
            -destination "platform=$platform,name=$device" \
            FULL_DROPBOX_API_APP_KEY=$FULL_DROPBOX_API_APP_KEY \
            FULL_DROPBOX_API_APP_SECRET=$FULL_DROPBOX_API_APP_SECRET \
            FULL_DROPBOX_USER_OAUTH2_TOKEN=$FULL_DROPBOX_USER_OAUTH2_TOKEN \
            test
      - name: Test macOS
        env:
          FULL_DROPBOX_API_APP_KEY: ${{ secrets.FULL_DROPBOX_API_APP_KEY }}
          FULL_DROPBOX_API_APP_SECRET: ${{ secrets.FULL_DROPBOX_API_APP_SECRET }}
          FULL_DROPBOX_USER_OAUTH2_TOKEN: ${{ secrets.FULL_DROPBOX_USER_OAUTH2_TOKEN }}
          platform: ${{ 'macOS' }}
        run: |
          xcodebuild -workspace TestObjectiveDropbox/TestObjectiveDropbox.xcworkspace/ -scheme TestObjectiveDropbox_macOS  \
            -destination "platform=$platform,arch=x86_64" \
            FULL_DROPBOX_API_APP_KEY=$FULL_DROPBOX_API_APP_KEY \
            FULL_DROPBOX_API_APP_SECRET=$FULL_DROPBOX_API_APP_SECRET \
            FULL_DROPBOX_USER_OAUTH2_TOKEN=$FULL_DROPBOX_USER_OAUTH2_TOKEN \
            test
